version: '3.8'

services:
  django:
    container_name: django
    restart: always
    build: ./backend
    volumes:
      - static:/backend/static
    env_file:
      - backend/.env
    expose:
      - 8000
  nginx:
    build:
      context: ./backend
      dockerfile: Dockerfile_nginx
    restart: always
    volumes:
      - static:/static
    ports:
      - "50002:50002"
    depends_on:
      - django

volumes:
  static:
