version: '3.3'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgres/data/
    expose:
      - "${POSTGRES_PORT}"
    env_file:
      - .env
  django:
    restart: always
    build: ./backend
    volumes:
      - static:/backend/static
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - postgres
  nginx:
    build:
      context: ./backend
      dockerfile: Dockerfile_nginx
    restart: always
    volumes:
      - static:/static
    ports:
      - "50002:50002"
    depends_on:
      - django

volumes:
  static:
  pg_data:
