version: '3.3'

services:
  django:
    restart: always
    build: ./backend
    volumes:
      - app:/app
      - static:/app/static
    env_file:
      - .env
    expose:
      - 8000
  nginx:
    build:
      context: ./backend
      dockerfile: nginx.Dockerfile
    restart: always
    volumes:
      - static:/static
    ports:
      - "50002:50002"
    depends_on:
      - django

volumes:
  static:
  app:
