version: '3.8'

services:
  django:
    container_name: django
    restart: always
    build: ./backend
    volumes:
      - ./backend:/backend
    env_file:
      - backend/.env
    entrypoint: "/bin/sh -c ./entrypoint.sh"
    ports:
      - "8000:8000"
