# Generated by Django 4.1.2 on 2022-11-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_item_id_item_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='inventory',
            new_name='inventory_id',
        ),
    ]
