# Generated by Django 4.1.2 on 2022-10-17 06:06
import sys

from django.db import migrations

import os
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_alter_baseitems_created_at_and_more'),
    ]

    def create_items(apps, schema_editor):
        from core.utils import csv_to_json_data_migration
        from shop import models
        files = (
            "ItemsType", "BaseItems", "Ammo", "Devices",
            "Weapons", "Droids", "Engines", "Resources", "Ships",)
        a = models.BaseItems(**{'id': '1', 'name': 'Снаряд', 'en_name': 'GunShot', 'class_number': '3', 'cost': '3',
             'size': '0.00200000009', 'image': 'images\\Ammo\\GunBullet.png'})
        a.save()
        return
        for file in files:
            print("*" * 100, file)
            p = os.path.join('apps', 'shop', 'migrations', 'data', file + ".csv")
            data = csv_to_json_data_migration(p)
            for data_ in data:
                print(data_)
                model = getattr(models, file)
                model.objects.get_or_create(**data_)

    operations = [
        migrations.RunPython(create_items),
    ]
