# Generated by Django 3.2.9 on 2022-01-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='auth_key',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='auth_key'),
        ),
    ]
