# Generated by Django 3.2.9 on 2022-01-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='name')),
                ('auth_key', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='auth_key')),
                ('race', models.IntegerField(choices=[(1, 'Омоленианин (Красные)'), (2, 'Иррииец (Жёлтые)'), (3, 'Анид (Зелёные)'), (4, 'Медрамилл (Синие)')], verbose_name='Race')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
