# Generated by Django 3.2.9 on 2022-01-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='auth_key',
            field=models.CharField(db_index=True, max_length=32, null=True, unique=True, verbose_name='auth_key'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='race',
            field=models.IntegerField(choices=[(1, 'Омоленианин (Красные)'), (2, 'Иррииец (Жёлтые)'), (3, 'Анид (Зелёные)'), (4, 'Медрамилл (Синие)')], null=True, verbose_name='Race'),
        ),
    ]
