# Generated by Django 3.2.9 on 2022-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20220214_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='username'),
        ),
    ]
