# Generated by Django 4.1.2 on 2022-10-17 07:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItems',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('class_number', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('size', models.FloatField()),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('damage', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('reload_time', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('effects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('restrictions', models.JSONField()),
                ('max_health', models.IntegerField()),
                ('device_type', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('hyperjump_radius', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('max_health', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('effects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('max_energy', models.IntegerField()),
                ('weapon_slots', models.IntegerField()),
                ('device_slots', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('shields', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('radar', models.IntegerField()),
                ('restrictions', models.JSONField()),
                ('speed', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('effects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('droid_slots', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('auto_shots', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('reload_time', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('min_damage', models.IntegerField()),
                ('max_damage', models.IntegerField()),
                ('need_cpu', models.IntegerField()),
                ('effects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('max_health', models.IntegerField()),
                ('weapon_type', models.IntegerField()),
                ('ammo_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.ammo')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Droids',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('energy_cost', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('droid_type', models.IntegerField()),
                ('restrictions', models.JSONField()),
                ('max_health', models.IntegerField()),
                ('weapon_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.weapons')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
            bases=('shop.baseitems',),
        ),
    ]
