# Generated by Django 4.1.2 on 2022-10-19 01:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItems',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('en_name', models.CharField(max_length=100, verbose_name='En название')),
                ('class_number', models.IntegerField(verbose_name='Номер класса')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('size', models.FloatField(verbose_name='Размер')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('type', models.CharField(auto_created='ammo', max_length=20)),
                ('damage', models.IntegerField(verbose_name='Урон')),
            ],
            options={
                'verbose_name': 'Боекомплект',
                'verbose_name_plural': 'Боекомплект',
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('type', models.CharField(auto_created='device', max_length=20)),
                ('reload_time', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('effects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('max_health', models.IntegerField()),
                ('device_type', models.IntegerField()),
                ('restrictions', models.JSONField()),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('type', models.CharField(auto_created='engine', max_length=20)),
                ('hyperjump_radius', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('max_health', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('type', models.CharField(auto_created='resource', max_length=20)),
                ('effects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('type', models.CharField(auto_created='ship', max_length=20)),
                ('max_energy', models.IntegerField()),
                ('weapon_slots', models.IntegerField()),
                ('device_slots', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('shields', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('radar', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('effects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('droid_slots', models.IntegerField()),
                ('restrictions', models.JSONField()),
            ],
            options={
                'verbose_name': 'Корабль',
                'verbose_name_plural': 'Корабли',
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('type', models.CharField(auto_created='weapon', max_length=20)),
                ('auto_shots', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('reload_time', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('min_damage', models.IntegerField()),
                ('max_damage', models.IntegerField()),
                ('need_cpu', models.IntegerField()),
                ('effects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('max_health', models.IntegerField()),
                ('weapon_type', models.IntegerField()),
                ('restrictions', models.JSONField()),
                ('ammo_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ammo')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружие',
            },
            bases=('shop.baseitems',),
        ),
        migrations.CreateModel(
            name='Droids',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseitems')),
                ('type', models.CharField(auto_created='droid', max_length=20)),
                ('energy_cost', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('droid_type', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('restrictions', models.JSONField()),
                ('weapon_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.weapons')),
            ],
            options={
                'verbose_name': 'Дройд',
                'verbose_name_plural': 'Дройды',
            },
            bases=('shop.baseitems',),
        ),
    ]
