# Generated by Django 4.1.2 on 2022-10-16 03:47

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('classNumber', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('size', models.FloatField()),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
