# Generated by Django 4.1.2 on 2022-10-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ships',
            name='restrictions',
            field=models.JSONField(null=True),
        ),
    ]
